[workspace]
resolver = "2"
members = ["crates/uv-core", "crates/uv-project", "crates/uv-source", "crates/uv-comptime", "crates/uv-analysis", "crates/uv-parity", "crates/uvc", "crates/uv-tooling", "crates/uv-lsp"]

[workspace.package]
version = "0.4.0-alpha"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/blacklight-foundation/ultraviolet"

[profile.release]
debug = 1
