[package]
name = "uv-parity"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
uv-core = { path = "../uv-core" }
uv-project = { path = "../uv-project" }
uv-source = { path = "../uv-source" }
uv-comptime = { path = "../uv-comptime" }
uv-analysis = { path = "../uv-analysis" }
