#!/usr/bin/env python3
"""Generate crates/uv-core/src/generated/case_folding.rs from Unicode 15.0 CaseFolding.txt (statuses C and F)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tools" / "data" / "CaseFolding-15.0.0.txt"
OUT = ROOT / "crates" / "uv-core" / "src" / "generated" / "case_folding.rs"

rows = []
for line in SRC.read_text(encoding="utf-8").splitlines():
    line = line.split("#", 1)[0].strip()
    if not line:
        continue
    code, status, mapping = [part.strip() for part in line.split(";")[:3]]
    if status in ("C", "F"):
        rows.append((int(code, 16), [int(x, 16) for x in mapping.split()]))
rows.sort()
lines = [
    "// Generated by tools/gen_casefold.py from Unicode 15.0.0 CaseFolding.txt. Do not edit.",
    "",
    "pub static CASE_FOLDING: &[(u32, &[u32])] = &[",
]
for code, mapping in rows:
    lines.append(f"    (0x{code:X}, &[{', '.join(f'0x{m:X}' for m in mapping)}]),")
lines += ["];", ""]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"case folding rows={len(rows)}")
