#!/usr/bin/env python3
"""Generate crates/uv-core/src/generated/static_rules.rs from the reference's registry of
static rules: for each rule the judgment it concludes, the diagnostic id it names, and
whether one of its premises is bottom."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "ultraviolet" / "Bootstrap" / "Ultraviolet" / "src" / "00_core" / "generated" / "static_rule_registry.inc"
OUT = ROOT / "crates" / "uv-core" / "src" / "generated" / "static_rules.rs"

C_STRING = r'"((?:[^"\\]|\\.)*)"'
ROW = re.compile(r"^\s*\{" + C_STRING + r", " + C_STRING + r", (std::nullopt|" + C_STRING +
                 r"|std::string_view\(" + C_STRING + r"\)), .*, (true|false)\},$")


def rust_str(body: str) -> str:
    value = bytes(body, "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    families_block = text.split("kStaticJudgmentFamilies[] = {", 1)[1].split("};", 1)[0]
    families = re.findall(C_STRING, families_block)
    rows_block = text.split("kStaticRules[] = {", 1)[1]
    rows = []
    for line in rows_block.splitlines():
        if not line.strip().startswith("{"):
            continue
        match = ROW.match(line)
        if not match:
            raise SystemExit(f"unparsed row: {line[:120]}")
        diag = match.group(4) if match.group(4) is not None else match.group(5)
        rows.append((match.group(1), match.group(2), diag, match.group(6)))
    out = ["// Generated by tools/gen_static_rules.py from the reference's static rule registry. Do not edit.", "",
           "pub static STATIC_JUDGMENT_FAMILIES: &[&str] = &["]
    out += [f"    {rust_str(name)}," for name in families]
    out += ["];", "", "/// Rule id, the judgment it concludes, the diagnostic id it names, a bottom premise.",
            "pub static STATIC_RULES: &[(&str, &str, Option<&str>, bool)] = &["]
    for rule_id, family, diag, bottom in rows:
        diag_text = "None" if diag is None else f"Some({rust_str(diag)})"
        out.append(f"    ({rust_str(rule_id)}, {rust_str(family)}, {diag_text}, {bottom}),")
    out += ["];", ""]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"families={len(families)} rules={len(rows)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
