#!/usr/bin/env python3
"""Generate crates/uv-core/src/generated/diag_registry.rs from the reference C++ sources."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "ultraviolet" / "Bootstrap" / "Ultraviolet" / "src" / "00_core"
OUT = ROOT / "crates" / "uv-core" / "src" / "generated" / "diag_registry.rs"

C_STRING = r'"((?:[^"\\]|\\.)*)"'


def rust_str(c_literal_body: str) -> str:
    value = bytes(c_literal_body, "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_registry(text: str):
    rows_block = text.split("kDiagRegistryRows[] = {", 1)[1].split("};", 1)[0]
    map_block = text.split("kDiagIdCodeMapEntries[] = {", 1)[1].split("};", 1)[0]
    rows = re.findall(r"\{" + C_STRING + r",\s*" + C_STRING + r",\s*" + C_STRING + r"\}", rows_block)
    entries = re.findall(r"\{" + C_STRING + r",\s*" + C_STRING + r"\}", map_block)
    return rows, entries


def parse_obligations(text: str):
    helpers: dict[str, list[str]] = {}
    for match in re.finditer(
        r"static bool (Is\w+)\(\s*std::string_view code\)\s*\{(.*?)\n\}", text, re.S
    ):
        helpers[match.group(1)] = match.group(2)

    def codes_of(expr: str) -> list[str]:
        out: list[str] = []
        for token in re.finditer(r'code == "([^"]+)"|(Is\w+)\(code\)', expr):
            if token.group(1):
                out.append(token.group(1))
            else:
                out.extend(codes_of(helpers[token.group(2)]))
        return out

    body = text.split("static void RecordDiagnosticTableObligations(", 1)[1]
    body = body.split("\nvoid Emit(", 1)[0]
    groups = []
    for match in re.finditer(r"\n  if \((.*?)\) \{\n(.*?)\n  \}", body, re.S):
        codes = codes_of(match.group(1))
        ids = re.findall(r'RecordDiagnosticObligation\(\s*diag,\s*"([^"]+)"', match.group(2))
        if not codes or not ids:
            raise SystemExit(f"unparsed obligation block: {match.group(0)[:120]}")
        groups.append((codes, ids))
    expected = len(re.findall(r"\n  if \(", body))
    if expected != len(groups):
        raise SystemExit(f"obligation block count mismatch: {expected} vs {len(groups)}")
    return groups


def main() -> int:
    rows, entries = parse_registry((CORE / "generated" / "diag_registry.inc").read_text(encoding="utf-8"))
    groups = parse_obligations((CORE / "diagnostics.cpp").read_text(encoding="utf-8"))
    if [r[0] for r in rows] != sorted(r[0] for r in rows):
        raise SystemExit("registry rows are not sorted by code")

    lines = [
        "// Generated by tools/gen_diag_registry.py from the reference compiler. Do not edit.",
        "",
        "use crate::diagnostics::Severity;",
        "",
        "pub struct DiagRegistryRow {",
        "    pub code: &'static str,",
        "    pub severity: Severity,",
        "    pub condition: &'static str,",
        "}",
        "",
        "pub static DIAG_REGISTRY_ROWS: &[DiagRegistryRow] = &[",
    ]
    for code, severity, condition in rows:
        lines.append(
            f"    DiagRegistryRow {{ code: {rust_str(code)}, severity: Severity::{severity}, condition: {rust_str(condition)} }},"
        )
    lines += ["];", "", "pub static DIAG_ID_CODE_MAP: &[(&str, &str)] = &["]
    for diag_id, code in entries:
        lines.append(f"    ({rust_str(diag_id)}, {rust_str(code)}),")
    lines += ["];", "", "/// Diagnostic codes and the obligations recorded when one of them is emitted.", "pub type ObligationGroup = (&'static [&'static str], &'static [&'static str]);", "", "pub static DIAG_TABLE_OBLIGATIONS: &[ObligationGroup] = &["]
    for codes, ids in groups:
        code_list = ", ".join(f'"{c}"' for c in codes)
        id_list = ", ".join(f'"{i}"' for i in ids)
        lines.append(f"    (&[{code_list}], &[{id_list}]),")
    lines += ["];", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"rows={len(rows)} id_map={len(entries)} obligation_groups={len(groups)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
